# Name of the project and initial config info
name: "da_sales"
version: "1.0.0"
dbt-cloud:
  project-id: 70437463662273
  defer-env-id: 70437463666050 # UAT/Staging environment
config-version: 2

# This profile is only used by ./dbt/profiles.yml when running locally, not relevant for cloud runs.
profile: "tr995_us1_70437463662273"

vars:
  mesh_products_project: dna_data_products
  mesh_domain_project: dna_data_domain


# dbt_snowflake_query_tags: enables query tagging and comments for Snowflake query observability.
# See https://hub.getdbt.com/get-select/dbt_snowflake_query_tags/latest/
dispatch:
  - macro_namespace: dbt
    search_order:
      - da_sales
      - dbt_snowflake_query_tags
      - dbt

query-comment:
  comment: '{{ dbt_snowflake_query_tags.get_query_comment(node) }}'
  append: true  # Snowflake removes prefixed comments

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
